### ISSUE TITLE
how to preview already stored video?

### ISSUE THREAD

**Issue by ridislam** [ezra-obiwale/jq-preview-media#7]
Hello author, 
i want to know if I already have a video stored on my server then, how can I show the preview? can you share an example code?

**Comment by ezra-obiwale** [comment]
This has nothing to do with this library. Just use the video tag (see [MDN](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/video) and [W3S](https://www.w3schools.com/tags/tag_video.asp).

And sorry for the late response.
